swagger: '2.0'
schemes:
  - https
host: tinyuid.com
basePath: /api/
info:
  contact:
    email: contact@tinyuid.com
    name: TinyUID
    url: 'https://tinyuid.com/feedback'
  description: Paste a Long URL link to shorten it
  title: TinyUID.com
  version: 1.0.0
  x-apisguru-categories:
    - developer_tools
  x-origin:
    - format: swagger
      url: 'https://tinyuid.com/tinyuid-swagger.yaml'
      version: '2.0'
  x-providerName: tinyuid.com
externalDocs:
  url: 'https://tinyuid.com/docs'
consumes:
  - application/x-www-form-urlencoded
  - multipart/form-data
produces:
  - application/json
paths:
  /v1/shorten:
    post:
      parameters:
        - description: Link
          format: url
          in: formData
          name: url
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            properties:
              result_url:
                description: Short link
                format: url
                type: string
            required:
              - result_url
            type: object
      summary: Create short link
