swagger: '2.0'
schemes:
  - https
host: azure.local
info:
  description: Use these REST APIs for performing operations on logger entity Azure API Management deployment.The Logger entity in API Management represents an event sink that you can use to log API Management events. Currently the Logger entity supports logging API Management events to Azure EventHub.
  title: ApiManagementClient
  version: '2017-03-01'
  x-apisguru-categories:
    - cloud
  x-logo:
    url: 'https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png'
  x-origin:
    - format: swagger
      url: 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/apimanagement/control-plane/Microsoft.ApiManagement/preview/2017-03-01/apimloggers.json'
      version: '2.0'
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: apimanagement-apimloggers
  x-tags:
    - Azure
    - Microsoft
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  apim_key:
    in: header
    name: Authorization
    type: apiKey
security:
  - apim_key: []
parameters:
  LoggerIdParameter:
    description: Logger identifier. Must be unique in the API Management service instance.
    in: path
    maxLength: 256
    name: loggerid
    pattern: '^[^*#&+:<>?]+$'
    required: true
    type: string
    x-ms-parameter-location: method
paths:
  /loggers:
    get:
      description: Lists a collection of loggers in the specified service instance.
      externalDocs:
        url: 'https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-log-event-hubs'
      operationId: Logger_List
      parameters:
        - description: |-
            | Field | Supported operators    | Supported functions                         |
            |-------|------------------------|---------------------------------------------|
            | id    | ge, le, eq, ne, gt, lt | substringof, contains, startswith, endswith |
            | type  | eq                     |                                             |
          in: query
          name: $filter
          required: false
          type: string
        - description: Number of records to return.
          format: int32
          in: query
          minimum: 1
          name: $top
          required: false
          type: integer
          x-ms-parameter-location: method
        - description: Number of records to skip.
          format: int32
          in: query
          minimum: 0
          name: $skip
          required: false
          type: integer
          x-ms-parameter-location: method
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          type: string
      responses:
        '200':
          description: Lists a collection of Logger entities.
          schema:
            $ref: '#/definitions/LoggerCollection'
        default:
          description: Error response describing why the operation failed.
          schema:
            description: Error Body contract.
            properties:
              code:
                description: Service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
                type: string
              details:
                description: 'The list of invalid fields send in request, in case of validation error.'
                items:
                  description: Error Field contract.
                  properties:
                    code:
                      description: Property level error code.
                      type: string
                    message:
                      description: Human-readable representation of property-level error.
                      type: string
                    target:
                      description: Property name.
                      type: string
                type: array
              message:
                description: Human-readable representation of the error.
                type: string
      tags:
        - Loggers
      x-ms-examples:
        ApiManagementListLoggers:
          parameters:
            Accept: application/json
            api-version: '2017-03-01'
            apimBaseUrl: apimservice1.management.azure-api.net
          responses:
            '200':
              body:
                count: 2
                value:
                  - credentials:
                      connectionString: '{{Logger-Credentials-5a58bc31a40f7e10489292a5}}'
                      name: testeventhub3
                    description: first eventhub logger
                    id: /loggers/5a58bc28a40f7e10489292a3
                    isBuffered: true
                    loggerType: azureEventHub
                  - credentials:
                      connectionString: '{{Logger-Credentials-5a58bc39a40f7e104892931b}}'
                      name: testeventhub3
                    description: first eventhub logger
                    id: /loggers/5a58bc37a40f7e1048929319
                    isBuffered: true
                    loggerType: azureEventHub
      x-ms-odata: '#/definitions/LoggerContract'
      x-ms-pageable:
        nextLinkName: nextLink
  '/loggers/{loggerid}':
    delete:
      description: Deletes the specified logger.
      operationId: Logger_Delete
      parameters:
        - $ref: '#/parameters/LoggerIdParameter'
        - description: The entity state (Etag) version of the logger to delete. A value of "*" can be used for If-Match to unconditionally apply the operation.
          in: header
          name: If-Match
          required: true
          type: string
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          type: string
      responses:
        '204':
          description: The logger was successfully deleted.
        default:
          description: Error response describing why the operation failed.
          schema:
            description: Error Body contract.
            properties:
              code:
                description: Service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
                type: string
              details:
                description: 'The list of invalid fields send in request, in case of validation error.'
                items:
                  description: Error Field contract.
                  properties:
                    code:
                      description: Property level error code.
                      type: string
                    message:
                      description: Human-readable representation of property-level error.
                      type: string
                    target:
                      description: Property name.
                      type: string
                type: array
              message:
                description: Human-readable representation of the error.
                type: string
      tags:
        - Loggers
      x-ms-examples:
        ApiManagementDeleteLoggers:
          parameters:
            If-Match: '"AAAAAAAAF30="'
            api-version: '2017-03-01'
            apimBaseUrl: apimservice1.management.azure-api.net
            loggerid: 5a58bc70a40f7e1048929950
          responses:
            '204': {}
    get:
      description: Gets the details of the logger specified by its identifier.
      operationId: Logger_Get
      parameters:
        - $ref: '#/parameters/LoggerIdParameter'
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          type: string
      responses:
        '200':
          description: The response body contains the specified Logger entity.
          headers:
            ETag:
              description: Current entity state version. Should be treated as opaque and used to make conditional HTTP requests.
              type: string
          schema:
            $ref: '#/definitions/LoggerContract'
        default:
          description: Error response describing why the operation failed.
          schema:
            description: Error Body contract.
            properties:
              code:
                description: Service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
                type: string
              details:
                description: 'The list of invalid fields send in request, in case of validation error.'
                items:
                  description: Error Field contract.
                  properties:
                    code:
                      description: Property level error code.
                      type: string
                    message:
                      description: Human-readable representation of property-level error.
                      type: string
                    target:
                      description: Property name.
                      type: string
                type: array
              message:
                description: Human-readable representation of the error.
                type: string
      tags:
        - Loggers
      x-ms-examples:
        ApiManagementGetLoggers:
          parameters:
            Accept: application/json
            api-version: '2017-03-01'
            apimBaseUrl: apimservice1.management.azure-api.net
            loggerid: 5a58bc37a40f7e1048929319
          responses:
            '200':
              body:
                credentials:
                  connectionString: '{{Logger-Credentials-5a58bc39a40f7e104892931b}}'
                  name: testeventhub3
                description: first eventhub logger
                id: /loggers/5a58bc37a40f7e1048929319
                isBuffered: true
                loggerType: azureEventHub
    patch:
      description: Updates an existing logger.
      operationId: Logger_Update
      parameters:
        - $ref: '#/parameters/LoggerIdParameter'
        - description: Update parameters.
          in: body
          name: parameters
          required: true
          schema:
            $ref: '#/definitions/LoggerUpdateContract'
        - description: The entity state (Etag) version of the logger to update. A value of "*" can be used for If-Match to unconditionally apply the operation.
          in: header
          name: If-Match
          required: true
          type: string
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          type: string
      responses:
        '204':
          description: The existing logger was successfully updated.
        default:
          description: Error response describing why the operation failed.
          schema:
            description: Error Body contract.
            properties:
              code:
                description: Service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
                type: string
              details:
                description: 'The list of invalid fields send in request, in case of validation error.'
                items:
                  description: Error Field contract.
                  properties:
                    code:
                      description: Property level error code.
                      type: string
                    message:
                      description: Human-readable representation of property-level error.
                      type: string
                    target:
                      description: Property name.
                      type: string
                type: array
              message:
                description: Human-readable representation of the error.
                type: string
      tags:
        - Loggers
      x-ms-examples:
        ApiManagementPatchLoggers:
          parameters:
            If-Match: '"AAAAAAAAHDE="'
            api-version: '2017-03-01'
            apimBaseUrl: apimservice1.management.azure-api.net
            loggerid: 5a58bd45a40f7e104892a3aa
            parameters:
              credentials:
                connectionString: '{{EventHubConnectionString5a58bd47a40f7e104892a3b0}}'
                name: testeventhub3
          responses:
            '204': {}
    put:
      description: Creates or Updates a logger.
      operationId: Logger_CreateOrUpdate
      parameters:
        - $ref: '#/parameters/LoggerIdParameter'
        - description: Create parameters.
          in: body
          name: parameters
          required: true
          schema:
            $ref: '#/definitions/LoggerContract'
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          type: string
      responses:
        '200':
          description: The existing logger was successfully updated.
          schema:
            $ref: '#/definitions/LoggerContract'
        '201':
          description: Logger was successfully created.
          schema:
            $ref: '#/definitions/LoggerContract'
        default:
          description: Error response describing why the operation failed.
          schema:
            description: Error Body contract.
            properties:
              code:
                description: Service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
                type: string
              details:
                description: 'The list of invalid fields send in request, in case of validation error.'
                items:
                  description: Error Field contract.
                  properties:
                    code:
                      description: Property level error code.
                      type: string
                    message:
                      description: Human-readable representation of property-level error.
                      type: string
                    target:
                      description: Property name.
                      type: string
                type: array
              message:
                description: Human-readable representation of the error.
                type: string
      tags:
        - Loggers
      x-ms-examples:
        ApiManagementPutLoggers:
          parameters:
            api-version: '2017-03-01'
            apimBaseUrl: apimservice1.management.azure-api.net
            loggerid: 5a58bc28a40f7e10489292a3
            parameters:
              credentials:
                connectionString: 'Endpoint=sb://contoso.servicebus.windows.net/;SharedAccessKeyName=SendPolicy;SharedAccessKey=sdfsdfdf'
                name: testeventhub3
              description: first eventhub logger
              loggerType: azureEventHub
          responses:
            '200':
              body:
                credentials:
                  connectionString: '{{Logger-Credentials-5a58bc31a40f7e10489292a5}}'
                  name: testeventhub3
                description: first eventhub logger
                id: /loggers/5a58bc28a40f7e10489292a3
                isBuffered: true
                loggerType: azureEventHub
            '201':
              body:
                credentials:
                  connectionString: '{{Logger-Credentials-5a58bc31a40f7e10489292a5}}'
                  name: testeventhub3
                description: first eventhub logger
                id: /loggers/5a58bc28a40f7e10489292a3
                isBuffered: true
                loggerType: azureEventHub
definitions:
  LoggerCollection:
    description: Paged Logger list representation.
    properties:
      count:
        description: Total record count number across all pages.
        format: int64
        type: integer
      nextLink:
        description: Next page link if any.
        type: string
      value:
        description: Logger values.
        items:
          $ref: '#/definitions/LoggerContract'
        type: array
  LoggerContract:
    allOf:
      - $ref: '#/definitions/LoggerContractProperties'
    description: Logger details.
    properties:
      id:
        description: Identifier of the Logger Entity.
        type: string
  LoggerContractProperties:
    description: The Logger entity in API Management represents an event sink that you can use to log API Management events. Currently the Logger entity supports logging API Management events to Azure Event Hubs.
    properties:
      credentials:
        additionalProperties:
          type: string
        description: The name and SendRule connection string of the event hub.
        example:
          connectionString: 'Endpoint=sb://contoso-ns.servicebus.windows.net/;SharedAccessKeyName=Sender;SharedAccessKey=...'
          name: apim
        type: object
      description:
        description: Logger description.
        maxLength: 256
        type: string
      isBuffered:
        description: Whether records are buffered in the logger before publishing. Default is assumed to be true.
        type: boolean
      loggerType:
        description: Logger type.
        enum:
          - azureEventHub
        type: string
        x-ms-enum:
          modelAsString: true
          name: LoggerType
          values:
            - description: Azure Event Hub as log destination.
              value: azureEventHub
    required:
      - loggerType
      - credentials
  LoggerUpdateContract:
    description: Parameters supplied to the Update Logger operation.
    properties:
      credentials:
        additionalProperties:
          type: string
        description: Logger credentials.
        type: object
      description:
        description: Logger description.
        type: string
      isBuffered:
        description: Whether records are buffered in the logger before publishing. Default is assumed to be true.
        type: boolean
      loggerType:
        description: Logger type.
        enum:
          - azureEventHub
        type: string
        x-ms-enum:
          modelAsString: true
          name: LoggerType
          values:
            - description: Azure Event Hub as log destination.
              value: azureEventHub
x-ms-parameterized-host:
  hostTemplate: '{apimBaseUrl}'
  parameters:
    - description: 'The management endpoint of the API Management service, for example https://myapimservice.management.azure-api.net.'
      in: path
      name: apimBaseUrl
      required: true
      type: string
      x-ms-skip-url-encoding: true
  positionInOperation: first
  useSchemePrefix: false
