swagger: '2.0'
schemes:
  - https
host: azure.local
info:
  title: Common types
  version: '1.0'
  x-apisguru-categories:
    - cloud
  x-logo:
    url: 'https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png'
  x-origin:
    - format: swagger
      url: 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/security/resource-manager/common/v1/types.json'
      version: '2.0'
  x-providerName: azure.com
  x-serviceName: security-types
  x-tags:
    - Azure
    - Microsoft
parameters:
  ApiVersion:
    description: API version for the operation
    in: query
    name: api-version
    required: true
    type: string
  AscLocation:
    description: The location where ASC stores the data of the subscription. can be retrieved from Get locations
    in: path
    name: ascLocation
    required: true
    type: string
    x-ms-parameter-location: client
  ODataExpand:
    description: OData expand. Optional.
    in: query
    name: $expand
    required: false
    type: string
    x-ms-parameter-location: method
  ODataFilter:
    description: OData filter. Optional.
    in: query
    name: $filter
    required: false
    type: string
    x-ms-parameter-location: method
  ODataSelect:
    description: OData select. Optional.
    in: query
    name: $select
    required: false
    type: string
    x-ms-parameter-location: method
  ResourceGroupName:
    description: The name of the resource group within the user's subscription. The name is case insensitive.
    in: path
    maxLength: 90
    minLength: 1
    name: resourceGroupName
    pattern: '^[-\w\._\(\)]+$'
    required: true
    type: string
    x-ms-parameter-location: method
  ResourceId:
    description: The identifier of the resource.
    in: path
    name: resourceId
    required: true
    type: string
    x-ms-parameter-location: method
  Scope:
    description: 'Scope of the query, can be subscription (/subscriptions/0b06d9ea-afe6-4779-bd59-30e5c2d9d13f) or management group (/providers/Microsoft.Management/managementGroups/mgName).'
    in: path
    name: scope
    required: true
    type: string
    x-ms-parameter-location: method
  SubscriptionId:
    description: Azure subscription ID
    in: path
    name: subscriptionId
    pattern: '^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$'
    required: true
    type: string
paths: {}
definitions:
  AscLocation:
    allOf:
      - $ref: '#/definitions/Resource'
    description: The ASC location of the subscription is in the "name" field
    properties:
      properties:
        $ref: '#/definitions/AscLocationProperties'
        x-ms-client-flatten: true
    type: object
  AscLocationList:
    description: List of locations where ASC saves your data
    properties:
      nextLink:
        description: The URI to fetch the next page.
        readOnly: true
        type: string
      value:
        items:
          $ref: '#/definitions/AscLocation'
        readOnly: true
        type: array
    type: object
  AscLocationProperties:
    description: An empty set of properties
    type: object
  AzureResourceDetails:
    allOf:
      - $ref: '#/definitions/ResourceDetails'
    description: Details of the Azure resource that was assessed
    properties:
      id:
        description: Azure resource Id of the assessed resource
        readOnly: true
        type: string
    type: object
    x-ms-discriminator-value: Azure
  CloudError:
    description: Error response structure.
    properties:
      error:
        $ref: '#/definitions/CloudErrorBody'
        description: Error data
        x-ms-client-flatten: true
    type: object
    x-ms-external: true
  CloudErrorBody:
    description: Error details.
    properties:
      code:
        description: An identifier for the error. Codes are invariant and are intended to be consumed programmatically.
        readOnly: true
        type: string
      message:
        description: 'A message describing the error, intended to be suitable for display in a user interface.'
        readOnly: true
        type: string
    type: object
    x-ms-external: true
  ETag:
    description: Entity tag is used for comparing two or more entities from the same requested resource.
    properties:
      etag:
        description: Entity tag is used for comparing two or more entities from the same requested resource.
        type: string
    type: object
  Kind:
    description: Describes an Azure resource with kind
    properties:
      kind:
        description: Kind of the resource
        type: string
    type: object
  Location:
    description: Describes an Azure resource with location
    properties:
      location:
        description: Location where the resource is stored
        readOnly: true
        type: string
    type: object
  OnPremiseResourceDetails:
    allOf:
      - $ref: '#/definitions/ResourceDetails'
    description: Details of the On Premise resource that was assessed
    properties:
      machineName:
        description: The name of the machine
        type: string
      sourceComputerId:
        description: The oms agent Id installed on the machine
        type: string
      vmuuid:
        description: The unique Id of the machine
        type: string
      workspaceId:
        description: Azure resource Id of the workspace the machine is attached to
        type: string
    required:
      - workspaceId
      - vmuuid
      - sourceComputerId
      - machineName
    type: object
    x-ms-discriminator-value: OnPremise
  Resource:
    description: Describes an Azure resource.
    properties:
      id:
        description: Resource Id
        readOnly: true
        type: string
      name:
        description: Resource name
        readOnly: true
        type: string
      type:
        description: Resource type
        readOnly: true
        type: string
    type: object
    x-ms-azure-resource: true
  ResourceDetails:
    description: Details of the resource that was assessed
    discriminator: source
    properties:
      source:
        description: The platform where the assessed resource resides
        enum:
          - Azure
          - OnPremise
        type: string
        x-ms-enum:
          modelAsString: true
          name: source
          values:
            - description: Resource is in Azure
              value: Azure
            - description: Resource in an on premise machine connected to Azure cloud
              value: OnPremise
    required:
      - source
    type: object
  Tags:
    description: A list of key value pairs that describe the resource.
    properties:
      tags:
        additionalProperties:
          type: string
        description: A list of key value pairs that describe the resource.
        type: object
    type: object
  TrackedResource:
    allOf:
      - $ref: '#/definitions/Resource'
      - $ref: '#/definitions/Location'
      - $ref: '#/definitions/Kind'
      - $ref: '#/definitions/ETag'
      - $ref: '#/definitions/Tags'
    description: Describes an Azure tracked resource.
    type: object
