swagger: '2.0'
schemes:
  - https
host: azure.local
info:
  description: Use these REST APIs for performing operations on Identity Provider entity associated with your Azure API Management deployment. Setting up an external Identity Provider for authentication can help you manage the developer portal logins using the OAuth2 flow.
  title: ApiManagementClient
  version: '2017-03-01'
  x-apisguru-categories:
    - cloud
  x-logo:
    url: 'https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png'
  x-origin:
    - format: swagger
      url: 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/apimanagement/control-plane/Microsoft.ApiManagement/preview/2017-03-01/apimidentityprovider.json'
      version: '2.0'
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: apimanagement-apimidentityprovider
  x-tags:
    - Azure
    - Microsoft
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  apim_key:
    in: header
    name: Authorization
    type: apiKey
security:
  - apim_key: []
parameters:
  IdentityProviderNameParameter:
    description: Identity Provider Type identifier.
    enum:
      - facebook
      - google
      - microsoft
      - twitter
      - aad
      - aadB2C
    in: path
    name: identityProviderName
    required: true
    type: string
    x-ms-enum:
      modelAsString: true
      name: IdentityProviderType
      values:
        - description: Facebook as Identity provider.
          value: facebook
        - description: Google as Identity provider.
          value: google
        - description: Microsoft Live as Identity provider.
          value: microsoft
        - description: Twitter as Identity provider.
          value: twitter
        - description: Azure Active Directory as Identity provider.
          value: aad
        - description: Azure Active Directory B2C as Identity provider.
          value: aadB2C
    x-ms-parameter-location: method
paths:
  /identityProviders:
    get:
      description: Lists a collection of Identity Provider configured in the specified service instance.
      externalDocs:
        url: 'https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-aad#how-to-authorize-developer-accounts-using-azure-active-directory'
      operationId: IdentityProvider_List
      parameters:
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          type: string
      responses:
        '200':
          description: Lists a collection of Identity Providers.
          schema:
            $ref: '#/definitions/IdentityProviderList'
        default:
          description: Error response describing why the operation failed.
          schema:
            description: Error Body contract.
            properties:
              code:
                description: Service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
                type: string
              details:
                description: 'The list of invalid fields send in request, in case of validation error.'
                items:
                  description: Error Field contract.
                  properties:
                    code:
                      description: Property level error code.
                      type: string
                    message:
                      description: Human-readable representation of property-level error.
                      type: string
                    target:
                      description: Property name.
                      type: string
                type: array
              message:
                description: Human-readable representation of the error.
                type: string
      tags:
        - IdentityProvider
      x-ms-examples:
        ApiManagementListIdentityProviders:
          parameters:
            Accept: application/json
            api-version: '2017-03-01'
            apimBaseUrl: apimservice1.management.azure-api.net
          responses:
            '200':
              body:
                count: 0
                value: []
      x-ms-pageable:
        nextLinkName: null
  '/identityProviders/{identityProviderName}':
    delete:
      description: Deletes the specified identity provider configuration.
      operationId: IdentityProvider_Delete
      parameters:
        - $ref: '#/parameters/IdentityProviderNameParameter'
        - description: The entity state (Etag) version of the backend to delete. A value of "*" can be used for If-Match to unconditionally apply the operation.
          in: header
          name: If-Match
          required: true
          type: string
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          type: string
      responses:
        '204':
          description: The identity provider configuration was successfully deleted.
        default:
          description: Error response describing why the operation failed.
          schema:
            description: Error Body contract.
            properties:
              code:
                description: Service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
                type: string
              details:
                description: 'The list of invalid fields send in request, in case of validation error.'
                items:
                  description: Error Field contract.
                  properties:
                    code:
                      description: Property level error code.
                      type: string
                    message:
                      description: Human-readable representation of property-level error.
                      type: string
                    target:
                      description: Property name.
                      type: string
                type: array
              message:
                description: Human-readable representation of the error.
                type: string
      tags:
        - IdentityProvider
      x-ms-examples:
        ApiManagementDeleteIdentityProviders:
          parameters:
            If-Match: '*'
            api-version: '2017-03-01'
            apimBaseUrl: apimservice1.management.azure-api.net
            identityProviderName: aadB2C
          responses:
            '204': {}
    get:
      description: Gets the configuration details of the identity Provider configured in specified service instance.
      operationId: IdentityProvider_Get
      parameters:
        - $ref: '#/parameters/IdentityProviderNameParameter'
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          type: string
      responses:
        '200':
          description: The response body contains the specified IdentityProvider entity configuration details.
          headers:
            ETag:
              description: Current entity state version. Should be treated as opaque and used to make conditional HTTP requests.
              type: string
          schema:
            $ref: '#/definitions/IdentityProviderContract'
        default:
          description: Error response describing why the operation failed.
          schema:
            description: Error Body contract.
            properties:
              code:
                description: Service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
                type: string
              details:
                description: 'The list of invalid fields send in request, in case of validation error.'
                items:
                  description: Error Field contract.
                  properties:
                    code:
                      description: Property level error code.
                      type: string
                    message:
                      description: Human-readable representation of property-level error.
                      type: string
                    target:
                      description: Property name.
                      type: string
                type: array
              message:
                description: Human-readable representation of the error.
                type: string
      tags:
        - IdentityProvider
      x-ms-examples:
        ApiManagementGetIdentityProviders:
          parameters:
            Accept: application/json
            api-version: '2017-03-01'
            apimBaseUrl: apimservice1.management.azure-api.net
            identityProviderName: google
          responses:
            '200':
              body:
                clientId: FOLBTMWPUI
                clientSecret: GVGOUEEPZYUHRDIATOXM
                id: /identityProviders/Google
                type: google
    patch:
      description: Updates an existing IdentityProvider configuration.
      operationId: IdentityProvider_Update
      parameters:
        - $ref: '#/parameters/IdentityProviderNameParameter'
        - description: Update parameters.
          in: body
          name: parameters
          required: true
          schema:
            $ref: '#/definitions/IdentityProviderUpdateParameters'
        - description: The entity state (Etag) version of the identity provider configuration to update. A value of "*" can be used for If-Match to unconditionally apply the operation.
          in: header
          name: If-Match
          required: true
          type: string
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          type: string
      responses:
        '204':
          description: The existing identity provider configuration was successfully updated.
        default:
          description: Error response describing why the operation failed.
          schema:
            description: Error Body contract.
            properties:
              code:
                description: Service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
                type: string
              details:
                description: 'The list of invalid fields send in request, in case of validation error.'
                items:
                  description: Error Field contract.
                  properties:
                    code:
                      description: Property level error code.
                      type: string
                    message:
                      description: Human-readable representation of property-level error.
                      type: string
                    target:
                      description: Property name.
                      type: string
                type: array
              message:
                description: Human-readable representation of the error.
                type: string
      tags:
        - IdentityProviders
      x-ms-examples:
        ApiManagementPatchIdentityProviders:
          parameters:
            If-Match: '*'
            api-version: '2017-03-01'
            apimBaseUrl: apimservice1.management.azure-api.net
            identityProviderName: facebook
            parameters:
              clientId: BDNYXUKKLB
              clientSecret: QNFYIDJQVSGXDCXYLECG
          responses:
            '204': {}
    put:
      description: Creates or Updates the IdentityProvider configuration.
      operationId: IdentityProvider_CreateOrUpdate
      parameters:
        - $ref: '#/parameters/IdentityProviderNameParameter'
        - description: Create parameters.
          in: body
          name: parameters
          required: true
          schema:
            $ref: '#/definitions/IdentityProviderContract'
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          type: string
      responses:
        '200':
          description: The existing Identity Provider was successfully updated.
          schema:
            $ref: '#/definitions/IdentityProviderContract'
        '201':
          description: IdentityProvider configuration were successfully created.
          schema:
            $ref: '#/definitions/IdentityProviderContract'
        default:
          description: Error response describing why the operation failed.
          schema:
            description: Error Body contract.
            properties:
              code:
                description: Service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
                type: string
              details:
                description: 'The list of invalid fields send in request, in case of validation error.'
                items:
                  description: Error Field contract.
                  properties:
                    code:
                      description: Property level error code.
                      type: string
                    message:
                      description: Human-readable representation of property-level error.
                      type: string
                    target:
                      description: Property name.
                      type: string
                type: array
              message:
                description: Human-readable representation of the error.
                type: string
      tags:
        - IdentityProvider
      x-ms-examples:
        ApiManagementPutIdentityProviders:
          parameters:
            api-version: '2017-03-01'
            apimBaseUrl: apimservice1.management.azure-api.net
            identityProviderName: facebook
            parameters:
              clientId: BDNYXUKKLB
              clientSecret: QNFYIDJQVSGXDCXYLECG
              type: facebook
          responses:
            '200':
              body:
                clientId: BDNYXUKKLB
                clientSecret: QNFYIDJQVSGXDCXYLECG
                id: /identityProviders/Facebook
                type: facebook
            '201':
              body:
                clientId: BDNYXUKKLB
                clientSecret: QNFYIDJQVSGXDCXYLECG
                id: /identityProviders/Facebook
                type: facebook
definitions:
  IdentityProviderBaseParameters:
    description: Identity Provider Base Parameter Properties.
    properties:
      allowedTenants:
        description: List of Allowed Tenants when configuring Azure Active Directory login.
        items:
          type: string
        maxItems: 32
        type: array
      passwordResetPolicyName:
        description: Password Reset Policy Name. Only applies to AAD B2C Identity Provider.
        minLength: 1
        type: string
      profileEditingPolicyName:
        description: Profile Editing Policy Name. Only applies to AAD B2C Identity Provider.
        minLength: 1
        type: string
      signinPolicyName:
        description: Signin Policy Name. Only applies to AAD B2C Identity Provider.
        minLength: 1
        type: string
      signupPolicyName:
        description: Signup Policy Name. Only applies to AAD B2C Identity Provider.
        minLength: 1
        type: string
      type:
        description: Identity Provider Type identifier.
        enum:
          - facebook
          - google
          - microsoft
          - twitter
          - aad
          - aadB2C
        type: string
        x-ms-enum:
          modelAsString: true
          name: IdentityProviderType
          values:
            - description: Facebook as Identity provider.
              value: facebook
            - description: Google as Identity provider.
              value: google
            - description: Microsoft Live as Identity provider.
              value: microsoft
            - description: Twitter as Identity provider.
              value: twitter
            - description: Azure Active Directory as Identity provider.
              value: aad
            - description: Azure Active Directory B2C as Identity provider.
              value: aadB2C
  IdentityProviderContract:
    allOf:
      - $ref: '#/definitions/IdentityProviderContractProperties'
    description: Identity Provider details.
    properties:
      id:
        description: Identifier of the identity provider.
        type: string
  IdentityProviderContractProperties:
    allOf:
      - $ref: '#/definitions/IdentityProviderBaseParameters'
    description: 'The external Identity Providers like Facebook, Google, Microsoft, Twitter or Azure Active Directory which can be used to enable access to the API Management service developer portal for all users.'
    properties:
      clientId:
        description: 'Client Id of the Application in the external Identity Provider. It is App ID for Facebook login, Client ID for Google login, App ID for Microsoft.'
        minLength: 1
        type: string
      clientSecret:
        description: 'Client secret of the Application in external Identity Provider, used to authenticate login request. For example, it is App Secret for Facebook login, API Key for Google login, Public Key for Microsoft.'
        minLength: 1
        type: string
    required:
      - clientId
      - clientSecret
  IdentityProviderList:
    description: List of all the Identity Providers configured on the service instance.
    properties:
      count:
        description: Total number of identity providers
        type: integer
      value:
        description: Identity Provider configuration values.
        items:
          $ref: '#/definitions/IdentityProviderContract'
        type: array
  IdentityProviderUpdateParameters:
    allOf:
      - $ref: '#/definitions/IdentityProviderBaseParameters'
    description: Parameters supplied to the Update Identity Provider operation.
    properties:
      clientId:
        description: 'Client Id of the Application in the external Identity Provider. It is App ID for Facebook login, Client ID for Google login, App ID for Microsoft.'
        minLength: 1
        type: string
      clientSecret:
        description: 'Client secret of the Application in external Identity Provider, used to authenticate login request. For example, it is App Secret for Facebook login, API Key for Google login, Public Key for Microsoft.'
        minLength: 1
        type: string
x-ms-parameterized-host:
  hostTemplate: '{apimBaseUrl}'
  parameters:
    - description: 'The management endpoint of the API Management service, for example https://myapimservice.management.azure-api.net.'
      in: path
      name: apimBaseUrl
      required: true
      type: string
      x-ms-skip-url-encoding: true
  positionInOperation: first
  useSchemePrefix: false
