swagger: '2.0'
schemes:
  - https
host: azure.local
info:
  description: 'Use these REST APIs for performing operations on OpenId Connect Provider entity associated with your Azure API Management deployment. API Management allows you to access APIs secured with token from [OpenID Connect Provider ](http://openid.net/connect/) to be accessed from the Developer Console.'
  title: ApiManagementClient
  version: '2017-03-01'
  x-apisguru-categories:
    - cloud
  x-logo:
    url: 'https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png'
  x-origin:
    - format: swagger
      url: 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/apimanagement/control-plane/Microsoft.ApiManagement/preview/2017-03-01/apimopenidconnectproviders.json'
      version: '2.0'
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: apimanagement-apimopenidconnectproviders
  x-tags:
    - Azure
    - Microsoft
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  apim_key:
    in: header
    name: Authorization
    type: apiKey
security:
  - apim_key: []
parameters:
  OpenIdConnectIdParameter:
    description: Identifier of the OpenID Connect Provider.
    in: path
    maxLength: 256
    name: opid
    pattern: '^[^*#&+:<>?]+$'
    required: true
    type: string
    x-ms-parameter-location: method
paths:
  /openidConnectProviders:
    get:
      description: Lists all OpenID Connect Providers.
      operationId: OpenIdConnectProvider_List
      parameters:
        - description: |-
            | Field | Supported operators    | Supported functions                         |
            |-------|------------------------|---------------------------------------------|
            | id    | ge, le, eq, ne, gt, lt | substringof, contains, startswith, endswith |
            | name  | ge, le, eq, ne, gt, lt | substringof, contains, startswith, endswith |
          in: query
          name: $filter
          required: false
          type: string
        - description: Number of records to return.
          format: int32
          in: query
          minimum: 1
          name: $top
          required: false
          type: integer
          x-ms-parameter-location: method
        - description: Number of records to skip.
          format: int32
          in: query
          minimum: 0
          name: $skip
          required: false
          type: integer
          x-ms-parameter-location: method
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          type: string
      responses:
        '200':
          description: Lists of all the OpenId Connect Providers.
          schema:
            $ref: '#/definitions/OpenIdConnectProviderCollection'
      tags:
        - OpenIdConnectProviders
      x-ms-examples:
        ApiManagementListOpenIdConnectProvider:
          parameters:
            api-version: '2017-03-01'
            apimBaseUrl: apimservice1.management.azure-api.net
          responses:
            '200':
              body:
                count: 1
                value:
                  - clientId: oidprovidertemplate3
                    id: /openidConnectProviders/op1
                    metadataEndpoint: 'https://oidprovider-template3.net'
                    name: templateoidprovider3
      x-ms-odata: '#/definitions/OpenidConnectProviderContract'
      x-ms-pageable:
        nextLinkName: nextLink
  '/openidConnectProviders/{opid}':
    delete:
      description: Deletes specific OpenID Connect Provider of the API Management service instance.
      operationId: OpenIdConnectProvider_Delete
      parameters:
        - $ref: '#/parameters/OpenIdConnectIdParameter'
        - description: The entity state (Etag) version of the OpenID Connect Provider to delete. A value of "*" can be used for If-Match to unconditionally apply the operation.
          in: header
          name: If-Match
          required: true
          type: string
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          type: string
      responses:
        '204':
          description: OpenId Connect Provider was successfully deleted.
        default:
          description: Error response describing why the operation failed.
          schema:
            description: Error Body contract.
            properties:
              code:
                description: Service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
                type: string
              details:
                description: 'The list of invalid fields send in request, in case of validation error.'
                items:
                  description: Error Field contract.
                  properties:
                    code:
                      description: Property level error code.
                      type: string
                    message:
                      description: Human-readable representation of property-level error.
                      type: string
                    target:
                      description: Property name.
                      type: string
                type: array
              message:
                description: Human-readable representation of the error.
                type: string
      tags:
        - OpenIdConnectProviders
      x-ms-examples:
        ApiManagementDeleteOpenidconnectproviders:
          parameters:
            If-Match: '*'
            api-version: '2017-03-01'
            apimBaseUrl: apimservice1.management.azure-api.net
            opid: templateOpenIdConnect3
          responses:
            '204': {}
    get:
      description: Gets specific OpenID Connect Provider.
      operationId: OpenIdConnectProvider_Get
      parameters:
        - $ref: '#/parameters/OpenIdConnectIdParameter'
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          type: string
      responses:
        '200':
          description: The response body contains the specified OpenId Connect Provider entity.
          headers:
            ETag:
              description: Current entity state version. Should be treated as opaque and used to make conditional HTTP requests.
              type: string
          schema:
            $ref: '#/definitions/OpenidConnectProviderContract'
        default:
          description: Error response describing why the operation failed.
          schema:
            description: Error Body contract.
            properties:
              code:
                description: Service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
                type: string
              details:
                description: 'The list of invalid fields send in request, in case of validation error.'
                items:
                  description: Error Field contract.
                  properties:
                    code:
                      description: Property level error code.
                      type: string
                    message:
                      description: Human-readable representation of property-level error.
                      type: string
                    target:
                      description: Property name.
                      type: string
                type: array
              message:
                description: Human-readable representation of the error.
                type: string
      tags:
        - OpenIdConnectProviders
      x-ms-examples:
        ApiManagementGetOpenIdConnectProviders:
          parameters:
            api-version: '2017-03-01'
            apimBaseUrl: apimservice1.management.azure-api.net
            opid: op1
          responses:
            '200':
              body:
                clientId: oidprovidertemplate3
                id: /openidConnectProviders/op1
                metadataEndpoint: 'https://oidprovider-template3.net'
                name: templateoidprovider3
    patch:
      description: Updates the specific OpenID Connect Provider.
      operationId: OpenIdConnectProvider_Update
      parameters:
        - $ref: '#/parameters/OpenIdConnectIdParameter'
        - description: Update parameters.
          in: body
          name: parameters
          required: true
          schema:
            $ref: '#/definitions/OpenidConnectProviderUpdateContract'
        - description: The entity state (Etag) version of the OpenID Connect Provider to update. A value of "*" can be used for If-Match to unconditionally apply the operation.
          in: header
          name: If-Match
          required: true
          type: string
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          type: string
      responses:
        '204':
          description: OpenId Connect Provider was successfully updated.
        default:
          description: Error response describing why the operation failed.
          schema:
            description: Error Body contract.
            properties:
              code:
                description: Service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
                type: string
              details:
                description: 'The list of invalid fields send in request, in case of validation error.'
                items:
                  description: Error Field contract.
                  properties:
                    code:
                      description: Property level error code.
                      type: string
                    message:
                      description: Human-readable representation of property-level error.
                      type: string
                    target:
                      description: Property name.
                      type: string
                type: array
              message:
                description: Human-readable representation of the error.
                type: string
      tags:
        - OpenIdConnectProviders
      x-ms-examples:
        ApiManagementPatchOpenIdConnectProviders:
          parameters:
            If-Match: '*'
            api-version: '2017-03-01'
            apimBaseUrl: apimservice1.management.azure-api.net
            opid: templateOpenIdConnect2
            parameters:
              clientSecret: updatedsecret
          responses:
            '204': {}
    put:
      description: Creates or updates the OpenID Connect Provider.
      operationId: OpenIdConnectProvider_CreateOrUpdate
      parameters:
        - $ref: '#/parameters/OpenIdConnectIdParameter'
        - description: Create parameters.
          in: body
          name: parameters
          required: true
          schema:
            $ref: '#/definitions/OpenidConnectProviderContract'
        - description: Version of the API to be used with the client request.
          in: query
          name: api-version
          required: true
          type: string
      responses:
        '200':
          description: OpenIdConnect Provider was successfully updated.
          schema:
            $ref: '#/definitions/OpenidConnectProviderContract'
        '201':
          description: OpenIdConnect Provider was successfully created.
          schema:
            $ref: '#/definitions/OpenidConnectProviderContract'
        default:
          description: Error response describing why the operation failed.
          schema:
            description: Error Body contract.
            properties:
              code:
                description: Service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
                type: string
              details:
                description: 'The list of invalid fields send in request, in case of validation error.'
                items:
                  description: Error Field contract.
                  properties:
                    code:
                      description: Property level error code.
                      type: string
                    message:
                      description: Human-readable representation of property-level error.
                      type: string
                    target:
                      description: Property name.
                      type: string
                type: array
              message:
                description: Human-readable representation of the error.
                type: string
      tags:
        - OpenIdConnectProviders
      x-ms-examples:
        ApiManagementPutOpenIdConnectProviders:
          parameters:
            api-version: '2017-03-01'
            apimBaseUrl: apimservice1.management.azure-api.net
            opid: op1
            parameters:
              clientId: oidprovidertemplate3
              metadataEndpoint: 'https://oidprovider-template3.net'
              name: templateoidprovider3
          responses:
            '200':
              body:
                clientId: oidprovidertemplate3
                id: /openidConnectProviders/op1
                metadataEndpoint: 'https://oidprovider-template3.net'
                name: templateoidprovider3
            '201':
              body:
                clientId: oidprovidertemplate3
                id: /openidConnectProviders/op1
                metadataEndpoint: 'https://oidprovider-template3.net'
                name: templateoidprovider3
definitions:
  OpenIdConnectProviderCollection:
    description: Paged OpenIdProviders list representation.
    properties:
      count:
        description: Total number of entities
        type: integer
      nextLink:
        description: Next page link if any.
        type: string
      value:
        description: Page values.
        items:
          $ref: '#/definitions/OpenidConnectProviderContract'
        type: array
  OpenidConnectProviderContract:
    allOf:
      - $ref: '#/definitions/OpenidConnectProviderContractProperties'
    description: OpenId Connect Provider details.
    properties:
      id:
        description: Identifier of the OpenId Connect Provider.
        type: string
  OpenidConnectProviderContractProperties:
    description: OpenID Connect Providers Contract.
    properties:
      clientId:
        description: Client ID of developer console which is the client application.
        type: string
      clientSecret:
        description: Client Secret of developer console which is the client application.
        type: string
      description:
        description: User-friendly description of OpenID Connect Provider.
        type: string
      metadataEndpoint:
        description: Metadata endpoint URI.
        type: string
      name:
        description: User-friendly OpenID Connect Provider name.
        maxLength: 50
        type: string
    required:
      - name
      - metadataEndpoint
      - clientId
  OpenidConnectProviderUpdateContract:
    description: Parameters supplied to the Update OpenID Connect Provider operation.
    properties:
      clientId:
        description: Client ID of developer console which is the client application.
        type: string
      clientSecret:
        description: Client Secret of developer console which is the client application.
        type: string
      description:
        description: User-friendly description of OpenID Connect Provider.
        type: string
      metadataEndpoint:
        description: Metadata endpoint URI.
        type: string
      name:
        description: User-friendly OpenID Connect Provider name.
        maxLength: 50
        type: string
x-ms-parameterized-host:
  hostTemplate: '{apimBaseUrl}'
  parameters:
    - description: 'The management endpoint of the API Management service, for example https://myapimservice.management.azure-api.net.'
      in: path
      name: apimBaseUrl
      required: true
      type: string
      x-ms-skip-url-encoding: true
  positionInOperation: first
  useSchemePrefix: false
